"""initial

Revision ID: da97a0b62701
Revises: 
Create Date: 2026-03-03 01:08:14.171953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da97a0b62701'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('permissions', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('bulk_action_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_reference', sa.String(length=50), nullable=False),
    sa.Column('action_type', sa.Enum('FREEZE', 'UNFREEZE', 'RESTRICT', 'UNRESTRICT', 'SET_REVIEW', 'SET_APPROVED', 'SET_BLOCKED', 'ASSIGN', name='bulk_action_type_enum'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'PARTIAL', 'FAILED', name='bulk_job_status_enum'), nullable=False),
    sa.Column('initiated_by', sa.Integer(), nullable=False),
    sa.Column('total_merchants', sa.Integer(), nullable=True),
    sa.Column('processed_count', sa.Integer(), nullable=True),
    sa.Column('success_count', sa.Integer(), nullable=True),
    sa.Column('failure_count', sa.Integer(), nullable=True),
    sa.Column('merchant_ids', sa.JSON(), nullable=False),
    sa.Column('action_params', sa.JSON(), nullable=True),
    sa.Column('error_details', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['initiated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bulk_action_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bulk_action_jobs_job_reference'), ['job_reference'], unique=True)
        batch_op.create_index(batch_op.f('ix_bulk_action_jobs_status'), ['status'], unique=False)

    op.create_table('merchants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('merchant_id', sa.String(length=50), nullable=False),
    sa.Column('business_name', sa.String(length=200), nullable=False),
    sa.Column('legal_name', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('country', sa.String(length=3), nullable=False),
    sa.Column('business_type', sa.String(length=100), nullable=True),
    sa.Column('mcc_code', sa.String(length=10), nullable=True),
    sa.Column('monthly_volume', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('risk_score', sa.Integer(), nullable=True),
    sa.Column('risk_status', sa.Enum('REVIEW', 'APPROVED', 'BLOCKED', name='risk_status_enum'), nullable=False),
    sa.Column('is_frozen', sa.Boolean(), nullable=True),
    sa.Column('is_restricted', sa.Boolean(), nullable=True),
    sa.Column('restriction_reason', sa.String(length=500), nullable=True),
    sa.Column('flagged_at', sa.DateTime(), nullable=True),
    sa.Column('flagged_reason', sa.Text(), nullable=True),
    sa.Column('assigned_to', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('merchants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_merchants_country'), ['country'], unique=False)
        batch_op.create_index(batch_op.f('ix_merchants_is_frozen'), ['is_frozen'], unique=False)
        batch_op.create_index(batch_op.f('ix_merchants_merchant_id'), ['merchant_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_merchants_risk_status'), ['risk_status'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=50), nullable=True),
    sa.Column('merchant_id', sa.Integer(), nullable=True),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('bulk_job_id', sa.Integer(), nullable=True),
    sa.Column('previous_state', sa.JSON(), nullable=True),
    sa.Column('new_state', sa.JSON(), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['bulk_job_id'], ['bulk_action_jobs.id'], ),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_actor_id'), ['actor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_merchant_id'), ['merchant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_timestamp'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_merchant_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_entity_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_actor_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('merchants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_merchants_risk_status'))
        batch_op.drop_index(batch_op.f('ix_merchants_merchant_id'))
        batch_op.drop_index(batch_op.f('ix_merchants_is_frozen'))
        batch_op.drop_index(batch_op.f('ix_merchants_country'))

    op.drop_table('merchants')
    with op.batch_alter_table('bulk_action_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bulk_action_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_bulk_action_jobs_job_reference'))

    op.drop_table('bulk_action_jobs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('roles')
    # ### end Alembic commands ###
